{% set name = "mlx-lm" %}
{% set version = "0.31.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 61eb0e3ba09444f77f874aff295401d7ccd20b39495cbbce0c782a15474ce733

build:
  skip: true  # [py<310 or not (osx and arm64)]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - mlx >=0.31.2
    - numpy
    - transformers >=5.0.0
    - sentencepiece
    - protobuf
    - pyyaml
    - jinja2

test:
  imports:
    - mlx_lm
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/ml-explore/mlx-lm
  summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
  description: |
    MLX LM is a Python package for generating text and fine-tuning large language
    models on Apple silicon with MLX. Some key features include integration with
    the Hugging Face Hub to easily use thousands of LLMs with a single command,
    support for quantizing and uploading models to the Hugging Face Hub, low-rank
    and full model fine-tuning with support for quantized models, distributed
    inference and fine-tuning with mx.distributed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ml-explore/mlx-lm
  doc_url: https://github.com/ml-explore/mlx-lm

extra:
  recipe-maintainers:
    - conda-forge/mlx
    - sugatoray
